### ISSUE TITLE
telegram-notify document sending problem

### ISSUE THREAD

**Issue by tomi7711** [NicolasBernaerts/debian-scripts#23]
Hello!

The document sending (--document) doesn't work. When I'm using that parameter the message is not sent either.

Recently I tried with an older version, it worked.

Thanks!

**Comment by jacklul** [comment]
This is caused by curl command lines having both `--data` and `--form` parameters, mistake happened when `--data "parse_mode=${DISPLAY_MODE}"` was added to all command lines.

Fix: Replace `--data "parse_mode=${DISPLAY_MODE}"` with `--form parse_mode=${DISPLAY_MODE}` in lines 197 and 203.
@NicolasBernaerts

I've updated [my forked](https://github.com/jacklul/scripts/tree/main/telegram-notify) version to include this fix without version increment.

**Comment by tomi7711** [comment]
@jacklul Thanks!

**Comment by NicolasBernaerts** [comment]
@jacklul I've just corrected the script. Thanks.
@tomi7711 Could you confirm that it's now ok for you ?

**Comment by tomi7711** [comment]
> @jacklul I've just corrected the script. Thanks. @tomi7711 Could you confirm that it's now ok for you ?

Yep, it works perfectly!
